services:
  _defaults:
    autowire: true
    autoconfigure: true

  Mpc\MpcRss\:
    resource: '../Classes/*'

  # Extbase controllers must be public to be resolved by the container
  Mpc\MpcRss\Controller\:
    resource: '../Classes/Controller/*'
    public: true

  # FeedService must be public for Scheduler Tasks to resolve dependencies
  Mpc\MpcRss\Service\FeedService:
    public: true

  # Explicitly tag the command for Symfony Console
  Mpc\MpcRss\Command\UpdateFeedsCommand:
    tags:
      - name: 'console.command'
        command: 'mpcrss:updatefeeds'
        description: 'Update RSS feeds and refresh cache'
        schedulable: true


