services:
  _defaults:
    autowire: true
    autoconfigure: true

  Mpc\MpcRss\:
    resource: '../Classes/*'

  Mpc\MpcRss\Controller\:
    resource: '../Classes/Controller/*'
    public: true

  Mpc\MpcRss\Service\FeedService:
    public: true

  Mpc\MpcRss\Command\UpdateFeedsCommand:
    tags:
      - name: 'console.command'
        command: 'mpcrss:updatefeeds'
        description: 'Update RSS feeds and refresh cache'
        schedulable: true
